spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: false
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
route-management:
  base-url: http://route-management-service
