spring:
  application:
    name: route-management-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: false
  datasource:
    url: jdbc:postgresql://localhost:5433/dynamic_routes_demo
    username: demo_user
    password: demo_pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: health,info
