spring:
  application:
    name: route-management-service
  datasource:
    url: jdbc:postgresql://localhost:5433/dynamic_routes_demo
    username: demo_user
    password: demo_pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: health,info
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: false
eureka-api:
  base-url: http://localhost:8761/eureka/v2
